### ISSUE TITLE
Sell items

### ISSUE THREAD

**Issue by Rezanans-wow** [divios/Wards#8]
hi, what perms i need give for user?
Player try to sold or etc and got error 

- https://prnt.sc/1ryfzjt (Screenshot ERROR)

**Comment by divios** [comment]
Hi! I think you get the wrong repository, this is for the plugin wards, go to https://github.com/divios/DailyShop/issues. And that message is caused beacuse you have enabled the perms feature, it is explained here https://diviosx.gitbook.io/daily-random-shop/usage/item-customizer/permissions
